ContactInfo/ContactInfo.Web/Controllers/ContactsController.cs
using ContactInfo.Data.EFModels;
using ContactInfo.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContactInfo.Web.Controllers
{
    public class ContactsController : Controller
    {
        private IContactService iContactService;
        public ContactsController(IContactService icontactService)
        {
            iContactService = icontactService;
        }
        public ViewResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Add(Contact contacts)
        {
            try
            {
                contacts.Status = true;
                iContactService.Add(contacts);
            }
            catch(Exception ex)
            {
                return Json(new { Result = "False", Message = ex.Message });
            }
            return Json(new { Result = "True", Message = "Records Added" });
        }
        public JsonResult ContactList(int jtStartIndex, int jtPageSize, string jtSorting = null)
        {
            try
            {
              var contacts=  iContactService.List(jtStartIndex, jtPageSize, jtSorting);
                return Json(new { Result = "OK", Records = contacts, TotalRecordCount = contacts.Count });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        public JsonResult ActiveDeactive(int ContactId)
        {
            var contacts = iContactService.ActiveDeactive(ContactId);
            return Json(new { Result = "True" });
        }
        public JsonResult Delete(int ContactId)
        {
            var contacts = iContactService.Delete(ContactId);
            return Json(new { Result = "True" });
        }
        public JsonResult Update(Contact contacts)
        {
            try
            {
                iContactService.Update(contacts);
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
            return Json(new { Result = "OK" });
        }
    }
}

ContactInfo/ContactInfo.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContactInfo.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ContactInfo/ContactInfo.Web/Views/Contacts/Index.cshtml
@model ContactInfo.Data.EFModels.Contact
@{
    ViewBag.Title = "Index";
}


@using (Ajax.BeginForm("Add", "Contacts", new AjaxOptions { OnSuccess = "OnSuccess", OnFailure = "OnFailure" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add Contact</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <div id="ContactList"></div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        GetContacts();
    });
    function OnSuccess(data) {
        alert("Contact added successfully!.")
        GetContacts();
     }
    function OnFailure(data) {

    }
    function GetContacts() {

        $("#ContactList").jtable({
			title: '  ',
			paging: true,
			pageSize: 10,
			sorting: true,
            defaultSorting: 'ContactId Desc',
			actions: {
				listAction: '@Url.Action("../Contacts/ContactList")',
                updateAction: '@Url.Action("../Contacts/update")',
			},
			fields: {
                ContactId: {
					key: true,
					create: false,
					edit: false,
					list: false
				},
                FirstName: {
                    title: 'First Name',
					width: '15%'
                },
                LastName: {
                    title: 'Last Name',
                    width: '15%'
                },
                Email: {
                    title: 'Email',
                    width: '20%'
                },
                PhoneNumber: {
                    title: 'Phone Number',
                    width: '20%'
                }
                ,
                Status: {
                    title: 'Status',
                    width: '15%',
                    edit: false,
                    display: function (data) {
                        if (data.record.Status) {
                            return 'Active'
                        }
                        else {
                            return 'Deactive'
                        }
                    }
                },
                Action: {
                    title: 'Action',
                    width: '15%',
                    display: function (data) {
                        if (data.record.Status) {
                            return '<a href="#" onclick="ActiveDeactive(' + data.record.ContactId + ')">Deactivate</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href = "#" onclick = "OnDelete(' + data.record.ContactId +')">Delete</a >'
                        }
                        else {
                            return '<a href="#" onclick="ActiveDeactive(' + data.record.ContactId + ')">Activate</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href = "#" onclick = "OnDelete(' + data.record.ContactId +')">Delete</a >'
                        }
                    },
                    edit: false
                }
			}

		});
        $('#ContactList').jtable('load');
    }
    function ActiveDeactive(ContactId) {
        $.ajax({
            url: "../Contacts/ActiveDeactive",
            data: '{"ContactId":"' + ContactId + '"}',
            dataType: "JSON",
            type: "POST",
            contentType: "application/JSON; charset=utf-8",
            success: function (response) {
                if (response.Result) {

                        alert("Contact status updated successfully!.")

                    GetContacts();
                }
            }
        });
    }
    function OnDelete(ContactId) {
        $.ajax({
            url: "../Contacts/Delete",
            data: '{"ContactId":"' + ContactId + '"}',
            dataType: "JSON",
            type: "POST",
            contentType: "application/JSON; charset=utf-8",
            success: function (response) {
                if (response.Result) {

                    alert("Contact deleted successfully!.");
                    GetContacts();
                }
            }
        });
    }
</script>  

ContactInfo/ContactInfo.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ContactInfo/ContactInfo.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ContactInfo/ContactInfo.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ContactInfo/ContactInfo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Contact Info", "Index", "Contacts", new { area = "" }, new { @class = "navbar-brand" })
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    <script type="text/javascript" src="~/Scripts/jquery.jtable.js"></script>

    <link href="~/Content/jtable.css" rel="stylesheet" />

    @RenderSection("scripts", required: false)
</body>
</html>